"""Reader for the precomputed hilal history index.

``api/data/hilal_index.json`` holds one compact summary per sighting evening
(the same numbers ``/api/v1/hilal/info`` returns) for Hijri ``1444-08`` through
``1475-12``. It is generated by ``api/scripts/generate_hilal_index.py`` and lets
``/api/v1/hilal/history`` serve a whole range as a lookup.

An operator can point ``MABIMS_HILAL_INDEX`` at a newer file (e.g. one shipped
on the CDN volume) without rebuilding the image.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

logger = logging.getLogger("mabims.history")

BUNDLED = Path(__file__).resolve().parents[2] / "data" / "hilal_index.json"

_cache: dict | None = None


def _path() -> Path:
    override = os.environ.get("MABIMS_HILAL_INDEX")
    return Path(override) if override else BUNDLED


def index() -> dict:
    """Load (and memoise) the index. Empty dict when unavailable."""
    global _cache
    if _cache is not None:
        return _cache
    path = _path()
    try:
        _cache = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("history: index unavailable (%s): %s", path, exc)
        _cache = {}
    return _cache


def index_range() -> tuple[str, str] | None:
    rng = index().get("range") or {}
    first, last = rng.get("first"), rng.get("last")
    if not first or not last:
        return None
    return str(first), str(last)


def items(start: str | None = None, end: str | None = None) -> list[dict]:
    """Summaries for ``YYYY-MM`` keys within ``[start, end]``, oldest first."""
    months: dict = index().get("months") or {}
    keys = sorted(months)
    if start:
        keys = [k for k in keys if k >= start]
    if end:
        keys = [k for k in keys if k <= end]
    return [months[k] for k in keys]


def version() -> str | None:
    value = index().get("version")
    return str(value) if value else None
